name: Build ROM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Build Tools
        run: make tools

      - name: Build ROM
        run: |
          make clean
          make
          
      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: poke_rom
          path: "*.gba"
